# Generated by Django 4.1.3 on 2022-12-08 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.IntegerField()),
                ('skewer', models.IntegerField()),
                ('packing_status', models.BooleanField(default=False)),
                ('packing_datetime', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100)),
                ('section', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no', models.IntegerField()),
                ('is_submit', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.question')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='question_list',
            field=models.ManyToManyField(blank=True, through='pallet.SectionQuestion', to='pallet.question'),
        ),
        migrations.CreateModel(
            name='PalletSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='section_list',
            field=models.ManyToManyField(blank=True, through='pallet.PalletSection', to='pallet.section'),
        ),
    ]
