# Generated by Django 4.1.3 on 2022-12-16 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=255)),
                ('delivery_date', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('loading', 'Loading'), ('wait_approve', 'Wait Aprrove'), ('approved', 'Approved')], default='loading', max_length=100)),
                ('ref_do_no', models.CharField(max_length=255, null=True)),
                ('total_qty', models.CharField(max_length=255, null=True)),
                ('invoice_no', models.CharField(max_length=255, null=True)),
                ('round', models.CharField(max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.CharField(max_length=255)),
                ('skewer', models.CharField(max_length=255)),
                ('pallet_string', models.CharField(max_length=255, null=True)),
                ('internal_pallet_no', models.CharField(max_length=10, null=True)),
                ('nw_gw', models.CharField(choices=[('0173', 'Unit1'), ('0473', 'Unit4')], max_length=100, null=True)),
                ('packing_status', models.BooleanField(default=False)),
                ('packing_datetime', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('finish_pack', 'Finish Pack'), ('repack', 'Repack'), ('shipped', 'Shipped'), ('finish_packing_list', 'Finish Packing List')], max_length=100, null=True)),
                ('question_type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=255)),
                ('type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100)),
                ('section', models.IntegerField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.IntegerField(default=1)),
                ('pallet_no', models.IntegerField(default=1)),
                ('month', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PalletQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100)),
                ('section', models.IntegerField()),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.questiontemplate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PalletPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncdata.prodinfohistory')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='part_list',
            field=models.ManyToManyField(blank=True, through='pallet.PalletPart', to='syncdata.prodinfohistory'),
        ),
        migrations.AddField(
            model_name='pallet',
            name='question_list',
            field=models.ManyToManyField(blank=True, through='pallet.PalletQuestion', to='pallet.questiontemplate'),
        ),
        migrations.CreateModel(
            name='DocumentPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.document')),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='pallet_list',
            field=models.ManyToManyField(blank=True, through='pallet.DocumentPallet', to='pallet.pallet'),
        ),
    ]
