# Generated by Django 4.1.3 on 2022-12-17 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0002_migrate_data_question_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='question_type',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100),
        ),
    ]
