# Generated by Django 4.1.3 on 2022-12-12 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0002_migrate_data_question_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='skewer',
            field=models.CharField(max_length=255),
        ),
    ]
