# Generated by Django 4.1.3 on 2022-12-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0003_document_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pallet',
            name='pallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pallet',
            name='skewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
