# Generated by Django 4.1.3 on 2022-12-12 12:23

from django.db import migrations, models

def migrate_running_number_data(apps, schema_editor):
    RunningNumber = apps.get_model('pallet', 'RunningNumber')
    RunningNumber.objects.create(doc_no=1, pallet_no=1)

class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0003_alter_pallet_pallet_alter_pallet_skewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.IntegerField(default=1)),
                ('pallet_no', models.IntegerField(default=1)),
                ('month', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='internal_pallet_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='nw_gw',
            field=models.CharField(choices=[('0173', 'Unit1'), ('0473', 'Unit4')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pallet',
            name='pallet_string',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(migrate_running_number_data),
    ]
