# Generated by Django 4.1.3 on 2022-12-13 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0004_runningnumber_pallet_internal_pallet_no_pallet_nw_gw_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doc_no', models.CharField(max_length=255)),
                ('delivery_date', models.CharField(max_length=100, null=True)),
                ('is_approve', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='status',
            field=models.CharField(choices=[('finish_pack', 'Finish Pack'), ('repack', 'Repack'), ('shipped', 'Shipped'), ('finish_packing_list', 'Finish Packing List')], max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DocumentPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ref_do_no', models.CharField(max_length=255, null=True)),
                ('total_qty', models.CharField(max_length=255, null=True)),
                ('invoice_no', models.CharField(max_length=255, null=True)),
                ('round', models.CharField(max_length=255, null=True)),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.document')),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='document',
            name='pallet_list',
            field=models.ManyToManyField(blank=True, through='pallet.DocumentPallet', to='pallet.pallet'),
        ),
    ]
