# Generated by Django 4.1.3 on 2023-02-20 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0005_document_last_approve_by_document_loading_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='clerk_approve_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='engineer_approve_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='leader_approve_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='manager_approve_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='operator_approve_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='reject_name',
            field=models.CharField(default='', max_length=350),
        ),
        migrations.AddField(
            model_name='document',
            name='reject_role',
            field=models.CharField(default='', max_length=350),
        ),
    ]
