# Generated by Django 4.1.3 on 2022-12-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pallet', '0005_document_pallet_status_documentpallet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='is_approve',
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('loading', 'Loading'), ('wait_approve', 'Wait Aprrove'), ('approved', 'Approved')], default='loading', max_length=100),
        ),
    ]
