# Generated by Django 4.1.3 on 2022-12-16 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0001_initial'),
        ('pallet', '0006_remove_document_is_approve_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pallet',
            name='question_type',
            field=models.CharField(choices=[('Domestic', 'Domestic'), ('Export', 'Export')], default='Domestic', max_length=100),
        ),
        migrations.CreateModel(
            name='PalletPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pallet.pallet')),
                ('part', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='syncdata.prodinfohistory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pallet',
            name='part_list',
            field=models.ManyToManyField(blank=True, through='pallet.PalletPart', to='syncdata.prodinfohistory'),
        ),
    ]
