# Generated by Django 4.1.3 on 2023-01-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_migrate_account_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Operator', 'Operator'), ('Leader', 'Leader'), ('Clerk', 'Clerk'), ('Engineer', 'Engineer'), ('Manager', 'Manager'), ('SAP_Operator', 'Sap Operator'), ('Administrator', 'Administrator')], default='Administrator', max_length=255),
        ),
    ]
