# Generated by Django 4.1.3 on 2022-12-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PSETSDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_no', models.DecimalField(decimal_places=15, max_digits=30, unique=True)),
                ('delivery_date', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_time', models.CharField(blank=True, max_length=255, null=True)),
                ('id_sharp', models.CharField(blank=True, max_length=255, null=True)),
                ('modelname', models.CharField(blank=True, max_length=255, null=True)),
                ('item_sharp', models.CharField(blank=True, max_length=255, null=True)),
                ('prod_seq', models.CharField(blank=True, max_length=255, null=True)),
                ('pallet_sharp', models.CharField(blank=True, max_length=255, null=True)),
                ('skewer_sharp', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProdInfoHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_no', models.CharField(max_length=255)),
                ('plan_prod_finish_ym', models.CharField(max_length=255)),
                ('model_code', models.CharField(blank=True, max_length=255, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('serial_no', models.CharField(blank=True, max_length=255, null=True)),
                ('country_code', models.CharField(blank=True, max_length=255, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_code', models.CharField(blank=True, max_length=255, null=True)),
                ('distributor_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('id_no', 'plan_prod_finish_ym')},
            },
        ),
    ]
