# Generated by Django 4.1.3 on 2022-12-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MSActualMonthlySeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('actual_work_month', models.DateTimeField(null=True)),
                ('actual_running_seq', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSReportSeq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('form_code', models.CharField(max_length=255, null=True)),
                ('last_report_no', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MSSequenceNo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('actual_work_month', models.DateTimeField(null=True)),
                ('sequence_no', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingIssuingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('id_no', models.IntegerField(null=True)),
                ('packing_sequence_no', models.IntegerField(null=True)),
                ('report_no', models.IntegerField(null=True)),
                ('issue_datetime', models.DateTimeField(null=True)),
                ('packing_unit', models.IntegerField(null=True)),
                ('model_code', models.CharField(max_length=255, null=True)),
                ('distributor_code', models.IntegerField(null=True)),
                ('model_name', models.CharField(max_length=255, null=True)),
                ('serial_no', models.CharField(max_length=255, null=True)),
                ('packing_style_code', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PackingIssuingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('report_no', models.IntegerField(null=True)),
                ('item_number', models.IntegerField(null=True)),
                ('item_description', models.CharField(max_length=255, null=True)),
                ('number_of_times', models.IntegerField(null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProdResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station_no', models.CharField(max_length=255, null=True)),
                ('plan_monthly_seq', models.IntegerField(null=True)),
                ('plan_monthlu_sub_seq', models.IntegerField(null=True)),
                ('lastest_monthly_seq', models.IntegerField(null=True)),
                ('latest_monthly_sub_seq', models.IntegerField(null=True)),
                ('id_no', models.CharField(max_length=255, null=True)),
                ('prod_stat_us', models.IntegerField(null=True)),
                ('no_work_sign', models.IntegerField(null=True)),
                ('actual_monthly_seq', models.IntegerField(null=True)),
                ('actual_monthly_sub_seq', models.CharField(max_length=255, null=True)),
                ('error_code', models.CharField(max_length=255, null=True)),
                ('error_msg', models.CharField(max_length=255, null=True)),
                ('create_date', models.DateTimeField(null=True)),
                ('create_by', models.CharField(max_length=255, null=True)),
                ('update_date', models.DateTimeField(null=True)),
                ('update_by', models.CharField(max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PSETSDataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('prod_seq', models.IntegerField(null=True)),
                ('delivery_date', models.CharField(max_length=255, null=True)),
                ('pallet', models.IntegerField(null=True)),
                ('skewer', models.IntegerField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
