# Generated by Django 4.1.3 on 2022-12-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogSyncData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('table', models.CharField(max_length=255)),
                ('detail', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterLoading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stopshipment_date', models.CharField(max_length=255, null=True)),
                ('model_code', models.CharField(max_length=255, null=True)),
                ('model_name', models.CharField(max_length=255, null=True)),
                ('serial_no', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
