# Generated by Django 4.1.3 on 2022-12-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('syncdata', '0002_logsyncdata_masterloading'),
    ]

    operations = [
        migrations.CreateModel(
            name='MSPackingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_id', models.CharField(max_length=255, unique=True)),
                ('model_code', models.CharField(max_length=255, null=True)),
                ('packing_style_code', models.CharField(max_length=255, null=True)),
                ('net_weight', models.IntegerField(null=True)),
                ('gross_weight', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
